# Generated by Django 5.0.1 on 2024-02-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, max_length=300, null=True, upload_to="contacts/contact/avatar/"
            ),
        ),
    ]
